### ISSUE TITLE
Basic repo integration

### ISSUE THREAD

**Issue by cnp0** [repomint/repomint-web#27]
Feature for selecting a repository.

**Comment by Pfed-prog** [comment]
Not sure if it is what you have in mind but github api works pretty well, for example, for listing languages of the repo: https://docs.github.com/en/rest/reference/repos#list-repository-languages
![Jump](https://user-images.githubusercontent.com/66903336/133975430-1f8822d9-2722-45ff-9d30-a298fa021c80.gif)

**Comment by idiglove** [comment]
Yep calling their api is pretty easy, what we need is to verify the user through oauth, they can only mint their own or collaborated repos

**Comment by idiglove** [comment]
done here https://github.com/repomint/repomint-web/pull/33
